[package]
name = "gloat"
version = "0.1.0"
authors = ["ferris <yupferris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "opengl32"
crate-type = ["dylib"]

[dependencies]
minifb = "0.13"
